/// Flutter icons Soccerplayer
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Soccerplayer
///      fonts:
///       - asset: fonts/Soccerplayer.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Soccerplayer {
  Soccerplayer._();

  static const _kFontFam = 'Soccerplayer';

  static const IconData soccer_player =
      const IconData(0xe800, fontFamily: _kFontFam);
}
