/// Flutter icons SoccerIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SoccerIcons
///      fonts:
///       - asset: fonts/SoccerIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class SoccerIcons {
  SoccerIcons._();

  static const _kFontFam = 'SoccerIcons';

  static const IconData goal = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData redCard = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData yellowCard =
      const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData substitution =
      const IconData(0xe803, fontFamily: _kFontFam);
}
